---
title: <center><strong> Web scraping using R </strong></center>
author: <center><strong> Christopher Maronga </strong></center>
date: <center><strong> `r format(Sys.time(), '%d %B, %Y')` </strong></center>
output: 
  html_document:
    number_sections: no
    code_folding: hide
    theme: united
    toc: yes
    toc_depth: 4
    toc_float:
      collapsed: yes
      smooth_scroll: yes
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = F, message = F,
                      echo = T, 
                      dpi = 180, 
                      fig.width = 12, 
                      fig.height = 8,
                      results = "asis")
```


# Introduction





# Loading packages

```{r packages}
library(DBI)  # R database interface
library(odbc)  # connection to odbc compatible database
library(RSQLite) # Backed driver for SQLite
library(RMySQL) # Backed driver for MySQL
library(tidyverse) # dplyr verbs and more
library(redcapAPI) # connecting to REDCap database
library(here)  # manage working directories
library(DT)
```












